# Generated by Django 3.0.2 on 2020-01-15 17:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pub_date',
            field=models.DateField(default=datetime.date(2020, 1, 15)),
        ),
    ]
